services:
  - type: web
    name: must-lecturer-system
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: your-planetscale-host
      - key: DB_USER
        value: your-planetscale-user
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: must_lecturer_system_db
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000